# Generated by Django 5.1.6 on 2025-03-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFromHomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('work_location', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('ip_address', models.CharField(max_length=100)),
                ('server_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Present', max_length=50)),
            ],
        ),
    ]
